### PR TITLE
convert tooling to Dist::Zilla Starter bundle

### PR DESCRIPTION
**Pull request by Grinnz**
Rather straightforward conversion. Pod and critic tests moved to author tests. Added a CONTRIBUTING.md to detail dzil usage.

### CODE REVIEW

**Comment by Grinnz** [comment]
@xsawyerx do you have any objection to doing this?

**Comment by xsawyerx** [comment]
Things I would probably be annoyed by:

* There's `{{NEXT}}` in the and in the `dist.ini` but also in the files themselves. I would have to figure out how to keep those in sync. I'd rather they be defined once.
* The prereqs are defined in multiple places, causing me (and possibly other contributors) the same confusion. Why not generate it from the `dist.ini` or prereqs file?

Otherwise, :+1: from me.

**Comment by Grinnz** [comment]
> * There's `{{NEXT}}` in the and in the `dist.ini` but also in the files themselves. I would have to figure out how to keep those in sync. I'd rather they be defined once.

Not sure what this means. Makefile.PL and META.json are generated so should not be touched by anyone but the releaser, as mentioned in CONTRIBUTING.md.

**Comment by Grinnz** [comment]
I can specify the prereqs in dist.ini instead of cpanfile if it would make things clearer.

**Comment by xsawyerx** [comment]
Okay, I think what might have confused me is that you're including the changes made by Dist::Zilla to the files, not the unedited files. Am I right?

**Comment by Grinnz** [comment]
Yes, LICENSE/Makefile.PL/META.json are generated/updated on release or `regenerate` command.

**Comment by Grinnz** [comment]
Prereqs are now specified via [prereqs file](https://metacpan.org/pod/Dist::Zilla::Plugin::PrereqsFile).

**Pull request merged**
