### PR TITLE
Add a command line option to make warnings fatal (Default off)

### PR DESCRIPTION
**Pull request by chrestomanci**
Fixes issue #40 (bug #93023 on RT)

Unit test updated to not expect warnings to be fatal. POD docs updated.

### CODE REVIEW

**Comment by xsawyerx** [comment]
The only thing I would change is removing the "not recommended" comment.

It's less about what whether you have dependencies, but more of whether others depend on you, which makes the comment incorrect.

I think making it non-default basically says we would prefer you wouldn't use fatal warnings.

**Comment by chrestomanci** [comment]
I don't mind removing the  "not recommended" comment, from the short options description, but I think that this option would benefit from a longer explanation somewhere else, with links to the blog posts from Peter Rabbitson and chromatic, to explain more fully why fatal warnings are a bad idea. Question is where?

In any case, I need to add an entry to the changelog about this change, as it does change the public API. I also need to add changelog entries for the other changes I have pushed recently.

**Comment by xsawyerx** [comment]
We could also remove the default fatal warnings. I'm not adverse to that.

**Comment by chrestomanci** [comment]
Seeing as this change affects the default behaviour of the module, I think the change should be prominently documented somewhere. Also some people will think that the new default is wrong and that best practice is to make warnings fatal.

My thinking is to add a couple of paragraphs to the main POD for the module along the lines of:

"Older versions of this module generated code that made warnings fatal [...] This is no longer the default, see option [...], See blog posts [link] and [link] for reasons why." [Summary explanation]

Would you mind if I made a post to the CPAN PR challenge mailing list about this?

**Comment by xsawyerx** [comment]
Not at all, though I don't see how the mailing list could resolve this. It's not meant for "Module::Starter development", it's meant for pull request challenge discussions (about providing pull requests, not specific features/changes in a module).

**Comment by chrestomanci** [comment]
I have removed the 'not recommended' comment from the POD of the command line option, and instead put a short explanation into the changes file, with a link to the blog post about it for a fuller explanaton.

**Comment by xsawyerx** [comment]
Great stuff! :+1:

**Pull request merged**
